dist: xenial
language: python
sudo: false
services:
  - postgresql

python:
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VERBOSITY=-1
    - DATABASE_NAME=testdb
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=
    - SECRET_KEY=_
    - GOOGLE_ANALYTICS_ID=UA-111111111

# command to install dependencies and setup project
before_script:
  - psql -c "CREATE DATABASE $DATABASE_NAME;" -U $DATABASE_USER
  - pip3 install pipenv
  - pipenv install --dev --three
  - mkdir log
  - cp laumproject/settings.py.sample laumproject/settings.py
  - pipenv run python ./manage.py migrate
  - pipenv run python ./manage.py collectstatic
  - pipenv run python ./manage.py compilemessages

# command to run tests
script:
  - pipenv run coverage erase
  - pipenv run ./manage.py test
  - pipenv run coverage run ./manage.py test
  - pipenv run coverage report

after_success: pipenv run codecov
