dist: xenial
language: python
sudo: false
services:
  - postgresql

python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
before_script:
  - psql -c "CREATE DATABASE laum;" -U postgres
  - export PIPENV_VERBOSITY=-1
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - export DATABASE_NAME=laum
  - export DATABASE_USER=postgres
  - export DATABASE_PASSWORD=
  - make init
  - make setup

# command to run tests
script: make test

after_success: pipenv run codecov
