dist: xenial
language: python
sudo: false
python:
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install:
  - make init

before_script:
  - cp laum/settings.py.sample laum/settings.py
  - sed -i -e "s/SECRET_KEY = '.*'/SECRET_KEY = '_'/" laum/settings.py
  - make setup

# command to run tests
script: make test

after_success: pipenv run codecov
