language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
# command to run tests
script:
  - ./manage.py test
