dist: xenial
language: python
sudo: false
services:
  - postgresql

python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VERBOSITY=-1
    - DATABASE_NAME=laumproject
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=
    - SECRET_KEY=_
    - GOOGLE_ANALYTICS_ID=UA-111111111
    - EMAIL_HOST_USER='noreply@laum.ir'
    - EMAIL_HOST_PASSWORD=1234QWer@

# command to install dependencies
before_script:
  - psql -c "CREATE DATABASE $DATABASE_NAME;" -U $DATABASE_USER
  - make initdev
  - make setup

# command to run tests
script: make test

after_success: pipenv run codecov
