# Generated by Django 2.1.2 on 2018-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_on'], 'verbose_name': 'صفحه', 'verbose_name_plural': 'صفحه'},
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text='درصورتی که نیاز به یادآوری توضیحاتی در آینده وجود دارد در این قسمت وارد کنید. برای مثال علت رد گزارش یا...', max_length=1024, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('processed', 'رسیدگی شده'), ('denied', 'رد شده')], default='pending', help_text='در تعیین وضیعت رسیدگی دقت کنید. این قسمت تنها یک بار قابل تفییر است.', max_length=32, verbose_name='وضعیت رسیدگی'),
        ),
    ]
