# Generated by Django 2.2.4 on 2019-08-22 14:40

from django.db import migrations, models
import django.db.models.deletion
import web.helpers
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('gid', models.CharField(db_index=True, default=web.models.generate_gid, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='global ID')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='refid',
        ),
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], db_index=True, default=web.helpers.get_active_lang, max_length=7, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], db_index=True, default=web.helpers.get_active_lang, max_length=7, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='report',
            name='rid',
            field=models.CharField(editable=False, max_length=32, null=True, unique=True, verbose_name='reference ID'),
        ),
        migrations.AddField(
            model_name='tag',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], db_index=True, default=web.helpers.get_active_lang, max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designate whether this page can include on the result list.', verbose_name='active status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='reference',
            field=models.CharField(blank=True, help_text="The name of the book, newspaper, magazine or website address, blog and... along with the author's name.", max_length=128, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', related_query_name='tag', to='web.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designate whether this tag can include on the result list.', verbose_name='active status'),
        ),
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web.Group', verbose_name='group'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('group', 'language')},
        ),
    ]
