# Generated by Django 2.1.1 on 2018-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=1024, null=True, verbose_name='توضیحات مدیر'),
        ),
    ]
