# Generated by Django 2.2.1 on 2019-05-27 12:57

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181116_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل نویسنده'),
        ),
        migrations.AlterField(
            model_name='page',
            name='event',
            field=models.CharField(blank=True, help_text='تاریخ یک رویداد مهم برای موضوع وارد شده به همراه محل وقوع.', max_length=128, verbose_name='رویداد مهم'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_caption',
            field=models.CharField(blank=True, help_text='مکان و موقعیت گرفتن عکس به همراه معرفی افراد حاضر در عکس.', max_length=128, verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='page',
            name='pid',
            field=models.CharField(default=web.models.generate_new_pid, max_length=16, unique=True, verbose_name='شناسه\u200cی عمومی'),
        ),
        migrations.AlterField(
            model_name='page',
            name='reference',
            field=models.CharField(blank=True, help_text='نام کتاب، روزنامه، مجله یا آدرس سایت، بلاگ و... به همراه نام نویسنده', max_length=128, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'تایید شده'), ('denied', 'رد شده')], default='pending', help_text='در تعیین وضیعت رسیدگی دقت کنید. این قسمت تنها یک بار قابل تفییر است.', max_length=32, verbose_name='وضعیت رسیدگی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(choices=[('site_slogan_1', 'شعار ۱'), ('site_slogan_2', 'شعار ۲'), ('default_keywords', 'کلید واژه\u200cهای پیش\u200cفرض'), ('default_description', 'توضیح پیش\u200cفرض'), ('contact_email', 'ایمیل ارتباطی'), ('notification_email', 'ایمیل اطلاع\u200cرسانی'), ('google_analytics_id', 'شناسه\u200cی Google Analytics')], help_text='از هر نوع فقط یک نمونه می\u200cتوانید ایجاد کنید.', max_length=32, unique=True, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='keyword',
            field=models.SlugField(allow_unicode=True, verbose_name='کلیدواژه'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام'),
        ),
    ]
