# Generated by Django 2.1.3 on 2018-11-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181102_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('site_title', 'عنوان سایت'), ('site_slogan_1', 'شعار ۱'), ('site_slogan_2', 'شعار ۲'), ('default_keywords', 'کلید واژه\u200cهای پیش\u200cفرض'), ('default_description', 'توضیح پیش\u200cفرض'), ('contact_email', 'ایمیل ارتباطی'), ('google_analytics_id', 'شناسه\u200cی Google Analytics')], help_text='از هر نوع فقط یک نمونه می\u200cتوانید ایجاد کنید.', max_length=32, unique=True, verbose_name='نوع')),
                ('content', models.CharField(help_text='محتوایی که در سایت نمایش داده می\u200cشود.', max_length=1024, verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
