# Generated by Django 2.2.1 on 2019-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190523_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'تایید شده'), ('denied', 'رد شده')], default='pending', help_text='در تعیین وضیعت رسیدگی دقت کنید. این قسمت تنها یک بار قابل تفییر است.', max_length=32, verbose_name='وضعیت رسیدگی'),
        ),
    ]
