# Generated by Django 2.0.6 on 2018-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=13, unique=True, verbose_name='public id')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('subtitle', models.CharField(max_length=128, null=True, verbose_name='subtitle')),
                ('content', models.TextField(max_length=384, verbose_name='content')),
                ('ann_date', models.CharField(max_length=128, null=True, verbose_name='anniversary date')),
                ('image', models.ImageField(null=True, upload_to='photos', verbose_name='image')),
                ('image_caption', models.CharField(max_length=128, null=True, verbose_name='image caption')),
                ('tags', models.CharField(max_length=128, verbose_name='tags')),
                ('reference', models.CharField(max_length=128, null=True, verbose_name='reference')),
                ('author', models.EmailField(max_length=128, null=True, verbose_name='author')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
